### ISSUE TITLE
python setup.py develop does not work

### ISSUE THREAD

**Issue by prabhuramachandran** [ioam/lancet#6]
`python setup.py develop` does not work out of the box with Python-2.7.x and Lancet.

**Comment by jlstevens** [comment]
I will look into this shortly!

 I would just note that for development, I don't use ``setup.py develop`` myself and would probably recommend  cloning the git repository instead. For instance, we would be happy to accept proposed improvements to Lancet via pull requests (i.e we recommend that you fork the Lancet git repository, make some changes and then submit a pull request).

That said, because I don't use this command myself it is possible I don't understand your use-case properly. What is it you would you like to use ``setup.py develop``for? 

Regardless, I will try to fix this issue if I can!

**Comment by jlstevens** [comment]
I hadn't noticed your PR. I assume you have tested it and therefore I am happy to merge it right away if you wish!
